// Dados de fallback usados enquanto o Supabase nao estiver configurado
// (gerados a partir do calendario de viagens 2026 original).
import type { Viagem } from './viagens';

export const viagensFallback: Viagem[] = [
  {
    "data_saida": "2026-05-01",
    "data_retorno": "2026-05-03",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Cláudia Câmara",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan Laray",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem direita",
    "cancelada": false
  },
  {
    "data_saida": "2026-05-08",
    "data_retorno": "2026-05-10",
    "regiao_rio": "Estrada",
    "responsavel_grupo": "Kinda",
    "grupo": "Avanço Missionário",
    "grupo_complemento": null,
    "coordenador": "Pr. Emerson",
    "barco_local": "ÔNIBUS",
    "observacoes": "Acertar o local com Pr. Emerson",
    "cancelada": false
  },
  {
    "data_saida": "2026-05-16",
    "data_retorno": "2026-05-23",
    "regiao_rio": "Rio Solimões",
    "responsavel_grupo": "AO",
    "grupo": "Creekside Church (Lutz, Flórida)",
    "grupo_complemento": null,
    "coordenador": "Pr. Emerson",
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-05-17",
    "data_retorno": "2026-05-23",
    "regiao_rio": "CANCELADA",
    "responsavel_grupo": "Bruno",
    "grupo": "WP BRASIL Agência Missionária",
    "grupo_complemento": null,
    "coordenador": "Pr. Emerson",
    "barco_local": "J. J. MESQUITA",
    "observacoes": null,
    "cancelada": true
  },
  {
    "data_saida": "2026-05-24",
    "data_retorno": "2026-05-30",
    "regiao_rio": "Anori",
    "responsavel_grupo": "Pr. Dilvan/Pr.Jay",
    "grupo": "Igreja Maranhão",
    "grupo_complemento": null,
    "coordenador": "Pr. Rogério",
    "barco_local": "J. J. MESQUITA",
    "observacoes": "Somente Evangelismo, Não havera atendimento",
    "cancelada": false
  },
  {
    "data_saida": "2026-05-29",
    "data_retorno": "2026-05-29",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Juciane",
    "grupo": "Universitários",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo Wilson",
    "barco_local": "Luz na Floresta",
    "observacoes": "Entrega de filtros Projeto Água Limpa",
    "cancelada": false
  },
  {
    "data_saida": "2026-05-30",
    "data_retorno": "2026-06-05",
    "regiao_rio": "Rio Unini",
    "responsavel_grupo": "AO",
    "grupo": "First Baptist Church (Tyler, Texas)",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan / Ev. Assis",
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-05-31",
    "data_retorno": "2026-06-06",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Dra. Aila",
    "grupo": "Igreja Presbiteriana Mosaico (Anapólis/GO)",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan",
    "barco_local": "J. J. MESQUITA",
    "observacoes": "Equipe tem 04 médicos e 03 dentistas",
    "cancelada": false
  },
  {
    "data_saida": "2026-06-12",
    "data_retorno": "2026-06-14",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Debora Mesquita",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem esquerda",
    "cancelada": false
  },
  {
    "data_saida": "2026-06-12",
    "data_retorno": "2026-06-18",
    "regiao_rio": "CANCELADA",
    "responsavel_grupo": "Pr. Edson",
    "grupo": "Igreja Presbiteriana Independente",
    "grupo_complemento": null,
    "coordenador": "Pr. Flávio / Dara",
    "barco_local": "J.J. MESQUITA",
    "observacoes": null,
    "cancelada": true
  },
  {
    "data_saida": "2026-06-12",
    "data_retorno": "2026-06-19",
    "regiao_rio": "Rio Uatumã",
    "responsavel_grupo": "AO",
    "grupo": "Citizens Church Family (Plano, Texas)",
    "grupo_complemento": "First Baptist Church of Palmetto (Palmetto, Flórida)",
    "coordenador": "Pr. Paulo / Ev. José Carlos",
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-06-13",
    "data_retorno": "2026-06-20",
    "regiao_rio": "URUCARÁ",
    "responsavel_grupo": "AO",
    "grupo": "New Beginnings Church (Longview, Texas)",
    "grupo_complemento": "First Baptist Church Burleson (Burleson, Texas)",
    "coordenador": "Pr. Paulo / Ev. Arício Jr.",
    "barco_local": "AMAZON / POÇO",
    "observacoes": "POÇO",
    "cancelada": false
  },
  {
    "data_saida": "2026-06-14",
    "data_retorno": "2026-06-24",
    "regiao_rio": "UNINI",
    "responsavel_grupo": "Branquinho",
    "grupo": "Igreja Sal da Terra",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan",
    "barco_local": "Ferreira Filho",
    "observacoes": "20 PESSOAS",
    "cancelada": false
  },
  {
    "data_saida": "2026-06-19",
    "data_retorno": "2026-06-21",
    "regiao_rio": "Estrada",
    "responsavel_grupo": "Juciane Seleguim",
    "grupo": "Avanço Missionário",
    "grupo_complemento": null,
    "coordenador": "Pr. Paulo Belan",
    "barco_local": "ÔNIBUS",
    "observacoes": "Acertar o local com Pr. Paulo Belan",
    "cancelada": false
  },
  {
    "data_saida": "2026-06-19",
    "data_retorno": "2026-06-25",
    "regiao_rio": "BERURI",
    "responsavel_grupo": "AO",
    "grupo": "South Spring Baptist Church (Tyler, Texas)",
    "grupo_complemento": "Northwestern College (Orange City, Iowa)",
    "coordenador": "Pr. Franklin",
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-06-21",
    "data_retorno": "2026-06-26",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "SUE / Pr. Thiago",
    "grupo": "Community Reformed - Sue",
    "grupo_complemento": null,
    "coordenador": "Pr. Rogério",
    "barco_local": "J.J. MESQUITA",
    "observacoes": "13 AMERICANOS",
    "cancelada": false
  },
  {
    "data_saida": "2026-06-28",
    "data_retorno": "2026-07-04",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Lucee Price",
    "grupo": "Northland Church",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "J.J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-07-03",
    "data_retorno": "2026-07-09",
    "regiao_rio": "MAUÉS",
    "responsavel_grupo": "AO",
    "grupo": "Coppell Bible Church (Coppell, Texas)",
    "grupo_complemento": null,
    "coordenador": "Pr. Daniel Carvalho",
    "barco_local": "AMAZON",
    "observacoes": "Equipe grande",
    "cancelada": false
  },
  {
    "data_saida": "2026-07-03",
    "data_retorno": "2026-07-05",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": null,
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan Laray",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem direita",
    "cancelada": false
  },
  {
    "data_saida": "2026-07-11",
    "data_retorno": "2026-07-18",
    "regiao_rio": "URUCARÁ",
    "responsavel_grupo": "Pr. Ryan - AO",
    "grupo": "New Hope Baptist Church (Cedar Park, Texas)",
    "grupo_complemento": null,
    "coordenador": "Pr. Paulo / Ev. Arício",
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-07-12",
    "data_retorno": "2026-07-18",
    "regiao_rio": "Rio Solimões",
    "responsavel_grupo": "Fernanda",
    "grupo": "MACKENZIE",
    "grupo_complemento": null,
    "coordenador": "Pr. Emerson",
    "barco_local": "J.J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-07-17",
    "data_retorno": "2026-07-23",
    "regiao_rio": "Rio Andirá",
    "responsavel_grupo": "AO",
    "grupo": "Carpenter's Way Church (Lufkin, Texas)",
    "grupo_complemento": null,
    "coordenador": "Pr. Mário",
    "barco_local": "AMAZON",
    "observacoes": "Dra. Vanessa",
    "cancelada": false
  },
  {
    "data_saida": "2026-07-20",
    "data_retorno": "2026-07-25",
    "regiao_rio": "Rio Amazonas",
    "responsavel_grupo": "Yuri / Opção 3",
    "grupo": "Igreja Presbiteriana Esperança (Vitória/ES)",
    "grupo_complemento": null,
    "coordenador": "Ev. Silvio",
    "barco_local": "J.J. MESQUITA",
    "observacoes": "22 pessoas - 05 médicos e 01 dentista",
    "cancelada": false
  },
  {
    "data_saida": "2026-07-25",
    "data_retorno": "2026-08-01",
    "regiao_rio": "BADAJÓS/Solimões",
    "responsavel_grupo": "AO",
    "grupo": "Bethel Bible Church",
    "grupo_complemento": null,
    "coordenador": "Pr. Rogério",
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-07-26",
    "data_retorno": "2026-08-01",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Sandra",
    "grupo": "TAMPA BAY",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "J.J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-07-26",
    "data_retorno": "2026-08-02",
    "regiao_rio": "SUPREMO",
    "responsavel_grupo": "Juciane",
    "grupo": "SMRT",
    "grupo_complemento": null,
    "coordenador": null,
    "barco_local": "EPV",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-08-07",
    "data_retorno": "2026-08-09",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Cláudia Camara",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem esquerda",
    "cancelada": false
  },
  {
    "data_saida": "2026-08-14",
    "data_retorno": "2026-08-16",
    "regiao_rio": "Estrada",
    "responsavel_grupo": "Kinda",
    "grupo": "Avanço Missionário",
    "grupo_complemento": null,
    "coordenador": "Pr. Emerson",
    "barco_local": "ÔNIBUS",
    "observacoes": "Acertar o local com Pr. Emerson",
    "cancelada": false
  },
  {
    "data_saida": "2026-08-09",
    "data_retorno": "2026-08-15",
    "regiao_rio": "CANCELADA",
    "responsavel_grupo": "Pr. Thiago",
    "grupo": "RCA",
    "grupo_complemento": null,
    "coordenador": "Evang. Silvio",
    "barco_local": "J.J. MESQUITA",
    "observacoes": null,
    "cancelada": true
  },
  {
    "data_saida": "2026-08-22",
    "data_retorno": "2026-08-22",
    "regiao_rio": "Manaus",
    "responsavel_grupo": "Juci/Lia/Carina",
    "grupo": "Crianças Igreja sede",
    "grupo_complemento": null,
    "coordenador": "Pr. Eustáquio",
    "barco_local": "EPV",
    "observacoes": "1º Corrida Missionária Kids",
    "cancelada": false
  },
  {
    "data_saida": "2026-08-29",
    "data_retorno": "2026-08-29",
    "regiao_rio": "Manuas",
    "responsavel_grupo": "Claudia",
    "grupo": "Membros da igreja",
    "grupo_complemento": null,
    "coordenador": "Pr. Eustáquio",
    "barco_local": "EPV",
    "observacoes": "Culto de Missões",
    "cancelada": false
  },
  {
    "data_saida": "2026-08-29",
    "data_retorno": "2026-09-06",
    "regiao_rio": "Nhamundá / Riozinho",
    "responsavel_grupo": "Pr. Thiago",
    "grupo": "First Reformed Orange City",
    "grupo_complemento": null,
    "coordenador": null,
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-09-04",
    "data_retorno": "2026-09-06",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Claudia Camera",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan Laray",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem direita",
    "cancelada": false
  },
  {
    "data_saida": "2026-09-11",
    "data_retorno": "2026-09-13",
    "regiao_rio": "CONFERÊNCIA",
    "responsavel_grupo": "Juciane",
    "grupo": "SMRT",
    "grupo_complemento": null,
    "coordenador": "Pr. Eustáquio",
    "barco_local": "EPV",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-09-13",
    "data_retorno": "2026-09-15",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "SMRT",
    "grupo": "VIAGEM DE VISÃO",
    "grupo_complemento": null,
    "coordenador": "Pr. Francisco",
    "barco_local": "J. J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-09-14",
    "data_retorno": "2026-09-18",
    "regiao_rio": "CTM",
    "responsavel_grupo": "Pr. Eustáquio / SMRT",
    "grupo": "CAPACITAÇÃO / PASTORES",
    "grupo_complemento": null,
    "coordenador": null,
    "barco_local": "CTM",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-09-18",
    "data_retorno": "2026-09-20",
    "regiao_rio": "Manacapuru",
    "responsavel_grupo": "Pr. Thiago / SMRT",
    "grupo": "CAPACITAÇÃO / Manacapuru",
    "grupo_complemento": null,
    "coordenador": null,
    "barco_local": null,
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-09-27",
    "data_retorno": "2026-10-03",
    "regiao_rio": "ITAPEAÇU",
    "responsavel_grupo": "Caio",
    "grupo": "CCC",
    "grupo_complemento": null,
    "coordenador": "Ev. Silvio",
    "barco_local": "J. J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-10-04",
    "data_retorno": "2026-10-10",
    "regiao_rio": "Rio Negro / ME",
    "responsavel_grupo": "Lucee Price",
    "grupo": "NORTHLAND",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "J.J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-10-11",
    "data_retorno": "2026-10-17",
    "regiao_rio": "Rio Negro / MD",
    "responsavel_grupo": "Dr. David",
    "grupo": "CALVARY",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan",
    "barco_local": "J. J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-10-18",
    "data_retorno": "2026-10-24",
    "regiao_rio": "Rio Negro / ME",
    "responsavel_grupo": null,
    "grupo": "STONE",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "J. J. MESQUITA",
    "observacoes": null,
    "cancelada": false
  },
  {
    "data_saida": "2026-10-30",
    "data_retorno": "2026-11-01",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Débora Mesquita",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem esquerda",
    "cancelada": false
  },
  {
    "data_saida": "2026-11-13",
    "data_retorno": "2026-11-15",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Cláudia Câmara",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan Laray",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem direita",
    "cancelada": false
  },
  {
    "data_saida": "2026-11-20",
    "data_retorno": "2026-11-22",
    "regiao_rio": "Estrada",
    "responsavel_grupo": "Kinda",
    "grupo": "Avanço Missionário",
    "grupo_complemento": null,
    "coordenador": "Pr. Paulo Belan",
    "barco_local": "ÔNIBUS",
    "observacoes": "Acertar o local com Pr. Paulo Belan",
    "cancelada": false
  },
  {
    "data_saida": "2026-11-27",
    "data_retorno": "2026-11-29",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Cláudia Câmara",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem esquerda",
    "cancelada": false
  },
  {
    "data_saida": "2026-12-04",
    "data_retorno": "2026-12-06",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Debora Mesquita",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Ivan Laray",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem direita",
    "cancelada": false
  },
  {
    "data_saida": "2026-12-11",
    "data_retorno": "2026-12-12",
    "regiao_rio": "Estrada",
    "responsavel_grupo": "Kinda",
    "grupo": "Avanço Missionário",
    "grupo_complemento": null,
    "coordenador": "Pr. Emerson",
    "barco_local": "ÔNIBUS",
    "observacoes": "Acertar o local com Pr. Emerson",
    "cancelada": false
  },
  {
    "data_saida": "2026-12-18",
    "data_retorno": "2026-12-19",
    "regiao_rio": "Rio Negro",
    "responsavel_grupo": "Debora Mesquita",
    "grupo": "Viagem das Equipes",
    "grupo_complemento": null,
    "coordenador": "Pr. Raimundo",
    "barco_local": "LUZ NA FLORESTA",
    "observacoes": "Somente margem esquerda",
    "cancelada": false
  },
  {
    "data_saida": "2026-12-28",
    "data_retorno": "2027-01-03",
    "regiao_rio": null,
    "responsavel_grupo": "AO",
    "grupo": "A CONFIRMAR - TYLER",
    "grupo_complemento": null,
    "coordenador": null,
    "barco_local": "AMAZON",
    "observacoes": null,
    "cancelada": false
  }
];
